### ISSUE TITLE
#2

### ISSUE THREAD

**Issue by novachok** [Zlangobelz/EPAM-php-lab#1]
https://github.com/Zlangobelz/EPAM-php-lab/blob/master/PHP%20%232%20-%20Strings/tasks.php#L4
ти мене дивєш - це не рішення - я очікую Camel style

https://github.com/Zlangobelz/EPAM-php-lab/blob/master/PHP%20%232%20-%20Strings/tasks.php#L11
це не рішення - воно не працює з "фыва олдж"

https://github.com/Zlangobelz/EPAM-php-lab/blob/master/PHP%20%232%20-%20Strings/tasks.php#L28
результат вірний, але рішення в край не оптимальне - за таке в проді - сварять

https://github.com/Zlangobelz/EPAM-php-lab/blob/master/PHP%20%232%20-%20Strings/tasks.php#L58
для рішення цієї задачі ви проходили відповідну функцію, замість циклу

**Comment by Zlangobelz** [comment]
шось якось розсіяно то все поробив. Навіть не замітив шо результат не такий як очікувався. Пардон

**Comment by Zlangobelz** [comment]
хух, виконано
